name: Daily Web Scraping

on:
  schedule:
    - cron: '0 16 * * *'  # Chạy vào 16:00 UTC hàng ngày
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: python scraper.py
      
    - name: Commit and push if content changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped content" && git push)
